# Generated by Django 4.1.7 on 2023-04-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcs_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='employee',
            new_name='employees',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='satrt_date',
            new_name='start_date',
        ),
    ]
