# Generated by Django 4.1.7 on 2023-04-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs_api', '0002_rename_employee_project_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(to='pcs_api.employee'),
        ),
    ]
