# Generated by Django 4.1.7 on 2023-04-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs_api', '0003_remove_project_employees_project_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
