# Generated by Django 4.2 on 2023-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs_api', '0004_alter_bill_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='bills',
            field=models.ManyToManyField(to='pcs_api.bill'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(to='pcs_api.task'),
        ),
    ]
